@startuml
'https://plantuml.com/class-diagram



package Personas{
class Usuario {
    String correo
    String contrasenia
    TarjetaDeCredito tarjeta
    List<Reserva> reserva

}

class Pasajero {
   String nombre
   String descripcion
}
}

package OperacionComercial{
class Compra{
    Usuario cliente
    List<Reserva> reservas
}
class Reserva{
    Itinerario itinerario
    Double tarifa

    void confirmar()
    Double getTarifa()
    void agregarReservaVuelo()
    void quitarReservaVuelo()

}

}

package Servicios{
class Vuelo{
    String estado
    Ciudad origen
    Ciudad destino
    int costo
    LocalDateTime fechaHorario
    List<Asiento> asiento
    List<Vuelo> vuelos
    Aerolinea aerolinea

    Boolean existenAsientosDisponibles()
    Boolean estaEnHora()
    void reservar(Usuario usuario)

}

class Asiento{
    Vuelo vuelo
    Boolean reservado
    CategoriaAsiento categoria

    void reservar()
}

enum CategoriaAsiento{
    PRIMERA_CLASE
    ECONOMICA

}

class Itinerario{
    List<Vuelo> vuelo
    Reserva reserva
    List<Pasajero> pasajeros
    List<Asiento> asientos


}


class Ciudad{
    String nombre
    String descripcion
}

class Aerolinea{
    List<Vuelo> vuelosQueOfrece
}

class RepositorioVuelos{

    List<Vuelo> devolverConsulta(Consulta consulta)
}
}

package Consultas{
class Consulta{
  Ciudad Origen
    Ciudad Destino

}

class ConsultaHorario{
    LocalDateTime inicio
    LocalDateTime fin

}
class ConsultaTarifa{
   String ordenTarifa
}
class ConsultaInfoVuelo{
    Vuelo vuelo
    LocalDateTime fechaHorario
    CategoriaAsiento categoria
    Aerolinea aerolinea
    boolean vueloDirecto
}
}



class TarjetaDeCredito{
   Usuario cliente
   boolean habilitado
   int numeroDeTarjeta
}



Usuario -->"*" Compra
Usuario --> TarjetaDeCredito



Compra -->"*" Reserva
Compra --> Usuario

Aerolinea -->"*" Vuelo

Reserva --> Itinerario


ConsultaHorario --|> Consulta
ConsultaTarifa --|> Consulta
ConsultaInfoVuelo--|> Consulta

Itinerario -->"*" Vuelo
Itinerario -->"*" Asiento
Itinerario -->"*" Pasajero

Vuelo -->"*" Asiento
Vuelo --> Ciudad
Vuelo --> Ciudad
Vuelo --> Aerolinea

Asiento --> CategoriaAsiento

RepositorioVuelos -->"*" Vuelo
RepositorioVuelos ..> Consulta

@enduml